version: '3.9'

services:
  mysql:
    image: mysql:8.4
    container_name: construtora_test_mysql
    restart: unless-stopped
    env_file:
      - ./.env.test.mysql
    ports:
      - "13307:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: construtora_test_backend
    restart: unless-stopped
    depends_on:
      - mysql
      - minio
    env_file:
      - ./.env.test.backend
    ports:
      - "18080:8080"

  frontend:
    image: node:20-alpine
    container_name: construtora_test_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./.env.test.frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "18081:5173"

  minio:
    image: minio/minio:latest
    container_name: construtora_test_minio
    restart: unless-stopped
    env_file:
      - ./.env.test.minio
    command: server /data --console-address ":9001"
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - minio_data_test:/data

volumes:
  mysql_data_test:
  minio_data_test:
