version: '3.9'

services:
  mysql:
    image: mysql:8.4
    container_name: construtora_mysql
    restart: unless-stopped
    env_file:
      - ./.env.local.mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: construtora_backend
    restart: unless-stopped
    depends_on:
      - mysql
      - minio
    env_file:
      - ./.env.local.backend
    ports:
      - "8080:8080"

  frontend:
    image: node:20-alpine
    container_name: construtora_frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./.env.local.frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "8081:5173"

  minio:
    image: minio/minio:latest
    container_name: construtora_minio
    restart: unless-stopped
    env_file:
      - ./.env.local.minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mysql_data:
  minio_data:
